server:
  port: 8081
  servlet:
    context-path: /shiro

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jsp.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
