spring:
    http:
        multipart:
            maxFileSize: 100Mb
            maxRequestSize: 100Mb
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
server:
    port: 8082