server:
  servlet:
    context-path: /thymeleaf
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.thymeleaf.entity
