server:
  port: 8081

spring:
  application:
    name: mall-authority
  profiles:
    active: dev
  #自定义spring security账户，配置指定的用户和密码
#  security:
#    user:
#      password: 123456 #默认是自动生成的一段字符串
#      name: cai        #默认是user

# swagger配置
#swagger:
#  # 是否开启swagger
#  enabled: true
#  title: mall_接口文档
#  # 全局统一鉴权配置
#  authorization:
#    key-name: mall

mybatis-plus:
  mapper-locations: classpath:/mapping/**/*Mapper.xml
  global-config:
    db-config:
      #设置实体id自增
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization  #JWT存储的请求头
  secret: mall-admin-secret   #JWT加解密使用的秘钥
  expiration: 604800      #JWT的超期限时间（60*60*24*7）
  tokenHead: 'Bearer '     #JWT负载中拿到开头（后面有空格）

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400  #24小时，此时时间单位是：秒

secure:
  ignored:
    urls:  #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /csrf
      - /error


