spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 3000ms
logging:
  level:
    root: info
    com:
      authority: debug
  file:
    name: D:/logs/app-api.log
#    path: D:/logs
#只配置 logging.path 会在指定路径下生成默认 spring.log文件
#同时配置上面两个属性：默认只有logging.file.name 生效