spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        #防止Message一直重新分发而导致内存泄漏
        retry:
          # 开启ack确认，默认是开启的，此处多余
          enabled: true
          # 重试次数 默认为3次
          max-attempts: 5
#      simple:
#        acknowledge-mode: manual #采用手动应答
#          concurrency: 1 #指定最小的消费者数量
#          max-concurrency: 1 #指定最大的消费者数量
    #消息发送到交换器确认
    publisher-confirms: true
    #消息发送到队列确认
    publisher-returns: true

