spring:
  application: turbine

turbine:
  aggregator:
    cluster-config: default
  app-config: product-view-service-feign  #配置Eureka中的serviceId列表，表明监控哪些服务。这里是把所有微服务名称是product-view-service-feign 的实例信息都收集起来
  cluster-name-expression: new String("default")

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
