server:
    port: 8085
    servlet:
        context-path: /thymeleaf
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/how2java?characterEncoding=UTF-8
        username: root
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML5
        servlet:
            content-type: text/html
