spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        #防止Message一直重新分发而导致内存泄漏
        retry:
          # 开启ack确认，默认是开启的，此处多余
          enabled: true
          # 重试次数 默认为3次
          max-attempts: 5