server:
  servlet:
    context-path: /shiro

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    mode: HTML
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:/mapping/*Mapper.xml
  type-aliases-package: com.shiro.entity
