mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

global-config:
  db-config:
    id-type: auto

server:
  port: 10020

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall-sc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8081 #指定控制台服务地址
        port: 8719 #跟控制台交流的端口，随意指定一个未使用的端口即可，默认为8719
      eager: true #取消控制台懒加载
      log:
        dir: ./logs #默认值${home}/logs/csp/
        switch-pid: true #日志带上线程id
  application:
    name: mall-order

#把Feign和Sentinel做个整合，这才是日常用法
feign:
  sentinel:
    enabled: true #开启Feign对Sentinel的支持

