spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        retry:
          # 开启ack确认，默认是开启的，此处多余
          enabled: true
          # 重试次数 默认为3次
          max-attempts: 5
    #消息发送到交换器确认
    publisher-confirms: true
    #消息发送到队列确认
    publisher-returns: true

