spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        retry:
          # 开启ack确认，默认是开启的，此处多余
          enabled: true
          # 重试次数 默认为3次
          max-attempts: 5




  spring.rabbitmq.listener.direct.retry.enabled=true

  spring.rabbitmq.listener.direct.retry.max-attempts=5

