spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mall-port
logging:
  level:
    #com.listenrobot.common.http.filter.HttpLoggingFilter: DEBUG
    org.springframework.data.mongodb.core: DEBUG