mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: com.shiro.pojo

server:
    context-path: /shiro
    port: 8083

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/shiro?characterEncoding=UTF-8
        username: root
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
