
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456

#springboot日志配置
logging:
  level:
    #root日志以INFO级别输出
    root: INFO
    #com.plus.dao包下所有class以DEBUG级别输出
    com.plus.dao: DEBUG

mybatis-plus:
  mapper-locations: classpath*:/**/*Mapper.xml
  global-config:
    db-config:
      #id自增
      id-type: auto
  #mybatis-plus日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
server:
  port: 8089